import Header from '@/components/header';
import Setting from '@/components/setting';
import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from 'next';
import './globals.css';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { useState } from 'react';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = cookies().get('mode');

  return (
    <html lang="ko">
      <body className={res && res.value === 'dark' ? 'dark-mode' : ''}>
        <StyledComponentsRegistry>
          <Setting>
            <Header mode={res?.value} />
            {children}
          </Setting>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
