import Header from '@/components/header';
import Setting from '@/components/setting';
import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <Setting>
            <Header />
            {children}
          </Setting>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
